### PR TITLE
Bifacialvf mismatch development

### PR DESCRIPTION
**Pull request by cdeline**
This is Silvana's PVMismatch analysis routine, being pulled into bifacialvf to integrate bifacial irradiance with mismatch analysis.

### CODE REVIEW

**Comment by cdeline** [comment]
Yay, green checkmark!

**Comment by cdeline** [comment]
@shirubana  - please confirm that the modules are working the way that you want them to.  We should think about some test cases for pytest to ensure that we get consistent output...  it would also help to document how the different modules are working..

**Comment by cdeline** [comment]
@shirubana : I've created a development tag at this point to version control our journal paper runs. 0.1.7_dev0

**Comment by shirubana** [comment]
@cdeline can you create a development tag at this point to vc the journal paper runs?  or at least after the "update to 72 cells"  
I want to add the version to the references~~.

(Also, merge? merge?)

**Comment by cdeline** [comment]
OK, I'm going to merge to development and create a tag for the purpose of documenting our Progress in PV work.  I'll probably take a closer look when we merge to master.

**Pull request merged**
