### PR TITLE
BUG: fix imports so they work

### LINKED ISSUE #15: imports don't work
when I try to run bifacial vf I get an import error:
```python
import bifacialvf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-7112b735b939> in <module>
----> 1 import bifacialvf

~\Projects\bifacialvf\bifacialvf\__init__.py in <module>
----> 1 from bifacialvf import simulate  # main program
      2 from vf import getBackSurfaceIrradiances, getFrontSurfaceIrradiances, getGroundShadeFactors  # main subroutines
      3 from vf import getSkyConfigurationFactors, trackingBFvaluescalculator, rowSpacing # helper functions
      4 from sun import hrSolarPos, perezComp, solarPos, sunIncident # solar position and value
      5 from loadVFresults import loadVFresults # utility for reading result files

ImportError: cannot import name 'simulate'
```

### PR DESCRIPTION
**Pull request by mikofski**
closes #15

### CODE REVIEW

**Comment by cdeline** [comment]
@mikofski  This pull request appears to do the same thing as #13 which was merged into development yesterday.  Can you confirm that this pull request is redundant?

**Comment by mikofski** [comment]
Not redundant exactly, but a prerequisite. #13 cleans up the doc strings, but for sphinx to work the imports needed to be fixed first. But yes in practice #13 already contains this PR, by necessity. Sorry.

**Comment by mikofski** [comment]
Other projects are very particular about mixing PRs, that's why I separated them, it makes the history easier to understand

**Comment by mikofski** [comment]
Closing since these changes were already merged in #13 (f8664273cdbb2c80a4e751731ebd04abda2dd9d0)

**Pull request closed without merging**
