### PR TITLE
Pandas as input to simulate

### PR DESCRIPTION
**Pull request by tcapelle**
I am proposing some changes to the simulate function, mainly to be able to ingest pandas dataframes as inputs with precomputed sunpositions. This is needed to be able to compare against other models.
I separated simulate in two functions:
- `simulate` (with the same function call as before)
- `simulate_inner`: The actual computing function that now takes a dataframe as input.
To do so, now simulate will call `read_tmy` to recover the file and transform it to a dataframe.

I have also added a new notebook showing the new API in 'docs/example_simulate_inner.ipynb'
Also, added a INES tmy file in `/data/tmy_ines.csv`

Some minor changes:
- Added tqdm to the iteration (replaced the while for a for)
- Removed some prints

### CODE REVIEW

**Comment by tcapelle** [comment]
I don't get what the option: `- REQ_ENV='--upgrade --upgrade-strategy=eager .'` does and why it does not install tqdm.

**Comment by shirubana** [comment]
I reviewed most of the changes, the only one I don't aggree on is the adding of the height (C) on the ideal rowspacing calculation (rowSpacing). This function is kinda useless anyways, but it tells you what separation "D" you need from the end of one module to the beginning of the next one for avoiding self-shading in fixed modules, which is independent of the clearance height of all the rows. 

For example, if modules are tilted at 0, then D = 0.
But with the addition of C, you don't get D = 0 ... etc.

I started changing how we deal with sunposition, I might merge your branch to mine. I however I have to discuss with @cdeline the bulk _simulate a sub-function of simulate .... I personally would prefer to give the user the ability of calling simulate with the dataframe already read on their own terms, or otherwise have that readTMY function kick in if the dataframe is not a dataframe and is an address on the computer. This is because I have my own versions of 'simulate' working with SRRL and pvdaq data and SNL data... so it's different every time :Q

**Comment by tcapelle** [comment]
Do you think this will be merged soon?

**Comment by cdeline** [comment]
It sounds like these features are covered in PR #30 and will be included in the next release.  I'm closing this for now, can re-open if the new release doesn't meet your needs.

**Pull request closed without merging**
